name: Release Drafter

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - id: tag
        uses: salsify/action-detect-and-tag-new-version@v2
        with:
          create-tag: false
          version-command: |
            eval $(egrep '^version=' libexec/anyenv---version) && echo "$version"
    outputs:
      current: ${{ steps.tag.outputs.current-version }}
      previous: ${{ steps.tag.outputs.previous-version }}

  publish_release:
    needs:
      - version
    if: needs.version.outputs.current != needs.version.outputs.previous
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - id: publish
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # publish: true
          version: ${{ needs.version.outputs.current }}
  
  update_release_draft:
    needs:
      - version
    if: needs.version.outputs.current == needs.version.outputs.previous
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - id: draft
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      draft-tag: ${{ steps.draft.outputs.tag_name }}
  
  update_bump_pull_request:
    needs: 
      - update_release_draft
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
